import { Normalize, Requirements, Style } from '../components/Design System';
import '../components/Design System/assets/scss/dist/normalize.css';
import { Setup } from '@/components/Design System';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

Style();
Normalize();
Requirements();
// Setup({ config: { normalize: false } });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <Setup config={{ normalize: false }} /> */}
      <body>{children}</body>
    </html>
  );
}
